beerinfo/urls.py
from django.contrib import admin
from django.urls import path

from beerinfo.views import (
    BarList,
    BarDetail,
    BarCreate,
    BarUpdate,
    BarDelete,
    BreweryList,
    BreweryDetail,
    BreweryCreate,
    BreweryUpdate,
    BreweryDelete,
    StaffList,
    StaffDetail,
    StaffCreate,
    StaffUpdate,
    StaffDelete,
    CustomerList,
    CustomerDetail,
    CustomerCreate,
    CustomerUpdate,
    CustomerDelete,
    BeerClassList,
    BeerClassDetail,
    BeerClassCreate,
    BeerClassUpdate,
    BeerClassDelete,
    BeerList,
    BeerDetail,
    BeerCreate,
    BeerUpdate,
    BeerDelete,
    PurchaseList,
    PurchaseDetail,
    PurchaseCreate,
    PurchaseUpdate,
    PurchaseDelete,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bar/',
         BarList.as_view(),
         name='beerinfo_bar_list_urlpattern'),
    path('bar/<int:pk>/',
         BarDetail.as_view(),
         name='beerinfo_bar_detail_urlpattern'),
    path('bar/create/',
         BarCreate.as_view(),
         name='beerinfo_bar_create_urlpattern'),
    path('bar/<int:pk>/update/',
         BarUpdate.as_view(),
         name='beerinfo_bar_update_urlpattern'),
    path('bar/<int:pk>/delete/',
         BarDelete.as_view(),
         name='beerinfo_bar_delete_urlpattern'),
    path('brewery/',
         BreweryList.as_view(),
         name='beerinfo_brewery_list_urlpattern'),
    path('brewery/<int:pk>/',
         BreweryDetail.as_view(),
         name='beerinfo_brewery_detail_urlpattern'),
    path('brewery/create/',
         BreweryCreate.as_view(),
         name='beerinfo_brewery_create_urlpattern'),
    path('brewery/<int:pk>/update/',
         BreweryUpdate.as_view(),
         name='beerinfo_brewery_update_urlpattern'),
    path('brewery/<int:pk>/delete/',
         BreweryDelete.as_view(),
         name='beerinfo_brewery_delete_urlpattern'),
    path('staff/',
         StaffList.as_view(),
         name='beerinfo_staff_list_urlpattern'),
    path('staff/<int:pk>/',
         StaffDetail.as_view(),
         name='beerinfo_staff_detail_urlpattern'),
    path('staff/create/',
         StaffCreate.as_view(),
         name='beerinfo_staff_create_urlpattern'),
    path('staff/<int:pk>/update/',
         StaffUpdate.as_view(),
         name='beerinfo_staff_update_urlpattern'),
    path('staff/<int:pk>/delete/',
         StaffDelete.as_view(),
         name='beerinfo_staff_delete_urlpattern'),
    path('customer/',
         CustomerList.as_view(),
         name='beerinfo_customer_list_urlpattern'),
    path('customer/<int:pk>/',
         CustomerDetail.as_view(),
         name='beerinfo_customer_detail_urlpattern'),
    path('customer/create/',
         CustomerCreate.as_view(),
         name='beerinfo_customer_create_urlpattern'),
    path('customer/<int:pk>/update/',
         CustomerUpdate.as_view(),
         name='beerinfo_customer_update_urlpattern'),
    path('customer/<int:pk>/delete/',
         CustomerDelete.as_view(),
         name='beerinfo_customer_delete_urlpattern'),
    path('beer_class/',
         BeerClassList.as_view(),
         name='beerinfo_beer_class_list_urlpattern'),
    path('beer_class/<int:pk>/',
         BeerClassDetail.as_view(),
         name='beerinfo_beer_class_detail_urlpattern'),
    path('beer_class/create/',
         BeerClassCreate.as_view(),
         name='beerinfo_beer_class_create_urlpattern'),
    path('beer_class/<int:pk>/update/',
         BeerClassUpdate.as_view(),
         name='beerinfo_beer_class_update_urlpattern'),
    path('beer_class/<int:pk>/delete/',
         BeerClassDelete.as_view(),
         name='beerinfo_beer_class_delete_urlpattern'),
    path('beer/',
         BeerList.as_view(),
         name='beerinfo_beer_list_urlpattern'),
    path('beer/<int:pk>/',
         BeerDetail.as_view(),
         name='beerinfo_beer_detail_urlpattern'),
    path('beer/create/',
         BeerCreate.as_view(),
         name='beerinfo_beer_create_urlpattern'),
    path('beer/<int:pk>/update/',
         BeerUpdate.as_view(),
         name='beerinfo_beer_update_urlpattern'),
    path('beer/<int:pk>/delete/',
         BeerDelete.as_view(),
         name='beerinfo_beer_delete_urlpattern'),
    path('purchase/',
         PurchaseList.as_view(),
         name='beerinfo_purchase_list_urlpattern'),
    path('purchase/<int:pk>/',
         PurchaseDetail.as_view(),
         name='beerinfo_purchase_detail_urlpattern'),
    path('purchase/create/',
         PurchaseCreate.as_view(),
         name='beerinfo_purchase_create_urlpattern'),
    path('purchase/<int:pk>/update/',
         PurchaseUpdate.as_view(),
         name='beerinfo_purchase_update_urlpattern'),
    path('purchase/<int:pk>/delete/',
         PurchaseDelete.as_view(),
         name='beerinfo_purchase_delete_urlpattern'),
]

twist_michelle_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView


urlpatterns = [

    path('',
         RedirectView.as_view(
             pattern_name="about_urlpattern",
             permanent=False
         )),
    path('login/',
         LoginView.as_view(template_name='beerinfo/login.html'),
         name='login_urlpattern'),
    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'),
    path('about/',
         TemplateView.as_view(
             template_name='beerinfo/about.html'),
         name='about_urlpattern'
         ),
    path('admin/', admin.site.urls),
    path('', include('beerinfo.urls'))
]

beerinfo/models.py
from django.db import models
from django.urls import reverse


class BeerClass(models.Model):
    beer_class_id = models.AutoField(primary_key=True)
    beer_class_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return '%s' % self.beer_class_name

    def get_absolute_url(self):
        return reverse('beerinfo_beer_class_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('beerinfo_beer_class_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_beer_class_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['beer_class_name']
        verbose_name_plural = "BeerClasses"


class Brewery(models.Model):
    brewery_id = models.AutoField(primary_key=True)
    brewery_name = models.CharField(max_length=45, unique=True)
    brewery_city = models.CharField(max_length=45)
    brewery_state = models.CharField(max_length=15)

    def __str__(self):
        return '%s, %s, %s' % (self.brewery_name, self.brewery_city, self.brewery_state)

    def get_absolute_url(self):
        return reverse('beerinfo_brewery_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('beerinfo_brewery_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_brewery_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['brewery_name', 'brewery_city', 'brewery_state']
        verbose_name_plural = "Breweries"


class Staff(models.Model):
    staff_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('beerinfo_staff_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('beerinfo_staff_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_staff_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name']
        unique_together = (('last_name', 'first_name'),)
        verbose_name_plural = "Staff"


class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('beerinfo_customer_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('beerinfo_customer_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_customer_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name']
        unique_together = (('last_name', 'first_name'),)


class Beer(models.Model):
    beer_id = models.AutoField(primary_key=True)
    beer_name = models.CharField(max_length=45, unique=True)
    beer_alc_content = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    beer_price = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    beer_class = models.ForeignKey(BeerClass, related_name='beers', on_delete=models.PROTECT)
    brewery = models.ForeignKey(Brewery, related_name='beers', on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.beer_name} ({self.beer_class}, {self.beer_alc_content}%)'

    def get_absolute_url(self):
        return reverse('beerinfo_beer_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('beerinfo_beer_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_beer_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['beer_name', 'beer_class__beer_class_name', 'beer_alc_content']
        #unique_together = (('semester', 'course', 'section_name'),)


class Bar(models.Model):
    bar_id = models.AutoField(primary_key=True)
    bar_name = models.CharField(max_length=45, unique=True)
    bar_city = models.CharField(max_length=45, default='')
    bar_state = models.CharField(max_length=2, default='')
    staff = models.ManyToManyField(Staff, related_name='bars', default='')
    beer = models.ManyToManyField(Beer, related_name='bars', default='')

    def __str__(self):
        return f'{self.bar_name}, {self.bar_city}, {self.bar_state}'

    def get_absolute_url(self):
        return reverse('beerinfo_bar_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('beerinfo_bar_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_bar_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['bar_name', 'bar_city', 'bar_state']
        unique_together = (('bar_name', 'bar_city', 'bar_state'),)


class Purchase(models.Model):
    purchase_id = models.AutoField(primary_key=True)
    quantity = models.IntegerField()
    beer = models.ForeignKey(Beer, related_name='purchases', on_delete=models.PROTECT, default='')
    customer = models.ForeignKey(Customer, related_name='purchases', on_delete=models.PROTECT)
    staff = models.ForeignKey(Staff, related_name='purchases', on_delete=models.PROTECT)
    bar = models.ForeignKey(Bar, related_name='purchases', on_delete=models.PROTECT, default='')

    def get_absolute_url(self):
        return reverse('beerinfo_purchase_detail_urlpattern',
                       kwargs={'pk': self.pk})
    
    def get_update_url(self):
        return reverse('beerinfo_purchase_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('beerinfo_purchase_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def total(self):
        total = self.beer.beer_price * self.quantity
        # for item in self.beer.all():
        #     total += (item.beer.beer_price * item.quantity)
        return total

    def __str__(self):
        return f'Bartender {self.staff.first_name} to customer {self.customer.first_name}, total is ${self.total()} at {self.bar}.'

beerinfo/forms.py
from django import forms

from beerinfo.models import Brewery, BeerClass, Beer, Staff, Customer, Bar, Purchase


class BreweryForm(forms.ModelForm):
    class Meta:
        model = Brewery
        fields = '__all__'

    def clean_brewery_name(self):
        return self.cleaned_data['brewery_name'].strip()

    def clean_brewery_city(self):
        return self.cleaned_data['brewery_city'].strip()

    def clean_brewery_state(self):
        return self.cleaned_data['brewery_state'].strip()


class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class BarForm(forms.ModelForm):
    class Meta:
        model = Bar
        fields = '__all__'

    def clean_bar_name(self):
        return self.cleaned_data['bar_name'].strip()

    def clean_bar_city(self):
        return self.cleaned_data['bar_city'].strip()

    def clean_bar_state(self):
        return self.cleaned_data['bar_state'].strip()


class BeerClassForm(forms.ModelForm):
    class Meta:
        model = BeerClass
        fields = '__all__'

    def clean_beer_class_name(self):
        return self.cleaned_data['beer_class_name'].strip()


class BeerForm(forms.ModelForm):
    class Meta:
        model = Beer
        fields = '__all__'

    def clean_beer_name(self):
        return self.cleaned_data['beer_name'].strip()

    # def clean_beer_alc_content(self):
    #     return self.cleaned_data['beer_alc_content'].strip()
    #
    # def clean_beer_price(self):
    #     return self.cleaned_data['beer_price'].strip()
    #
    # def clean_beer_class(self):
    #     return self.cleaned_data['beer_class'].strip()


class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'

beerinfo/templates/beerinfo/bar_detail.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Bar - {{ bar }}
{% endblock %}

{% block content %}
    <h2>{{ bar }}</h2>
    <ul class="inline">
        {% if perms.beerinfo.change_bar %}
            <li><a href="{{ bar.get_update_url }}"
                   class="button">
                    Edit Bar</a></li>
        {% endif %}
        {% if perms.beerinfo.delete_bar %}
            <li><a href="{{ bar.get_delete_url }}"
                   class="button">
                    Delete Bar</a></li>
        {% endif %}
    </ul>

    <section>
        <table>
            <tr>
                <th>Bar Name:</th>
                <td>{{ bar.bar_name }}</td>
            </tr>
            <tr>
                <th>Bar City:</th>
                <td>{{ bar.bar_city }}</td>
            </tr>
            <tr>
                <th>Bar State:</th>
                <td>{{ bar.bar_state }}</td>
            </tr>
        </table>
    </section>
    <section>
        <h3>Staff</h3>
        <ul>
            {% for staff in bar.staff.all %}
                <li>
                    <a href="{{ staff.get_absolute_url }}">{{ staff }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no staff for this bar.</em></li>
            {% endfor %}
        </ul>
    </section>
    <section>
        <h3>Beers</h3>
        <ul>
            {% for beer in bar.beer.all %}
                <li>
                    <a href="{{ beer.get_absolute_url }}">{{ beer }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no beers for this bar.</em></li>
            {% endfor %}
        </ul>
    </section>
    <p>
        Return to <a href="{% url 'beerinfo_bar_list_urlpattern' %}">Bar List</a>.
    </p>
{% endblock %}

beerinfo/templates/beerinfo/beer_class_list.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Beer Class List
{% endblock %}

{% block create_button %}
    {% if perms.beerinfo.add_beerclass %}
    <a
        href="{% url 'beerinfo_beer_class_create_urlpattern'  %}"
        class="button button-primary">
      Create New Beer</a>
    {% endif %}
{% endblock %}
{% block content %}
    {% if perms.beerinfo.add_beerclass %}
    <h2>Beer Class List</h2>
    <div>
        <a href="{% url 'beerinfo_beer_class_create_urlpattern' %}"
        class="button button-primary">
            Create New Beer Class
        </a>
    </div>
    {% endif %}
    <ul>
        {% for beer_class in beer_class_list %}
            <li>
                <a href="{{ beer_class.get_absolute_url }}">{{ beer_class }}</a>
            </li>
        {% empty %}
            <li>There are currently no beer classes available.</li>
        {% endfor %}
    </ul>
{% endblock %}

beerinfo/templates/beerinfo/beer_class_update.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Update Beer Class
{% endblock %}

{% block content %}
    <form
        action="{{ beer_class.get_update_url }} "
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Beer Class</button>
    </form>
{% endblock %}

beerinfo/templates/beerinfo/beer_detail.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Beer - {{  beer }}
{% endblock %}

{% block content %}
    <h2>{{ beer }}</h2>
    <ul class="inline">
        {% if perms.beerinfo.change_beer %}
            <li><a href="{{ beer.get_update_url }}"
                   class="button">
                    Edit Beer</a></li>
        {% endif %}
        {% if perms.beerinfo.delete_beer %}
            <li><a href="{{ beer.get_delete_url }}"
                   class="button">
                    Delete Beer</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Beer Name:</th>
                <td>{{ beer.beer_name }}</td>
            </tr>
            <tr>
                <th>Beer Class:</th>
                <td><a href="{{ beer_class.get_absolute_url }}">{{ beer_class }}</a> </td>
            </tr>
            <tr>
                <th>Beer Alcohol Content:</th>
                <td>{{ beer.beer_alc_content }}</td>
            </tr>
            <tr>
                <th>Beer Price:</th>
                <td>{{ beer.beer_price }}</td>
            </tr>
            <tr>
                <th>Brewery:</th>
                <td><a href="{{ brewery.get_absolute_url }}">{{ brewery }}</a> </td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Bars</h3>
        <ul>
            {% for bar in bar_list %}
                <li>
                    <a href="{{ bar.get_absolute_url }}">{{ bar }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no bars that serve this beer.</em></li>
            {% endfor %}
        </ul>
    </section>
    <p>
        Return to <a href="{% url 'beerinfo_beer_list_urlpattern' %}">Beer List</a>.
    </p>
{% endblock %}

beerinfo/templates/beerinfo/beer_form.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Create Beer
{% endblock %}

{% block content %}
    <form
        action="{% url 'beerinfo_beer_create_urlpattern' %}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Beer</button>
    </form>
{% endblock %}

beerinfo/templates/beerinfo/brewery_detail.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Brewery - {{  brewery }}
{% endblock %}

{% block content %}
    <h2>{{ brewery }}</h2>
    <ul class="inline">
        {% if perms.beerinfo.change_brewery %}
            <li><a href="{{ brewery.get_update_url }}"
                   class="button">
                    Edit Brewery</a></li>
        {% endif %}
        {% if perms.beerinfo.delete_brewery %}
            <li><a href="{{ brewery.get_delete_url }}"
                   class="button">
                    Delete Brewery</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Brewery Name:</th>
                <td>{{ brewery.brewery_name }}</td>
            </tr>
            <tr>
                <th>Brewery City:</th>
                <td>{{ brewery.brewery_city }}</td>
            </tr>
            <tr>
                <th>Brewery State:</th>
                <td>{{ brewery.brewery_state }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Beers</h3>
        <ul>
            {% for beer in beer_list %}
                <li>
                    <a href="{{ beer.get_absolute_url }}">{{ beer }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no beers for this brewery.</em></li>
            {% endfor %}
        </ul>
    </section>
    <p>
        Return to <a href="{% url 'beerinfo_brewery_list_urlpattern' %}">Brewery List</a>.
    </p>
{% endblock %}

beerinfo/templates/beerinfo/customer_confirm_delete.html
{% extends 'beerinfo/base.html' %}

{% block title %}
Delete Customer
{% endblock %}

{% block content %}
    <form
        action="{{ customer.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p> Are you sure that you want to delete customer {{ customer }}?
        </p>
        <a href="{{ customer.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Customer</button>
    </form>
{% endblock %}

beerinfo/templates/beerinfo/customer_list.html
{% extends 'beerinfo/base.html' %}
{% block title %}
    Bar List
{% endblock %}
{% block create_button %}
    {% if perms.beerinfo.add_customer %}
    <a
        href="{% url 'beerinfo_customer_create_urlpattern'  %}"
        class="button button-primary">
      Create New Customer</a>
    {% endif %}
{% endblock %}
{% block content %}
    <h2>Customer List</h2>
    {% if perms.beerinfo.add_customer %}
    <div>
        <a href="{% url 'beerinfo_customer_create_urlpattern' %}"
        class="button button-primary">
            Create New Customer
        </a>
    </div>
    {% endif %}
    <ul>
        {% for customer in customer_list %}
            <li>
                <a href="{{ customer.get_absolute_url }}">{{ customer }}</a>
            </li>
        {% empty %}
            <li>There are currently no customers available.</li>
        {% endfor %}
    </ul>
{% endblock %}

beerinfo/templates/beerinfo/login.html
{% extends 'beerinfo/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

beerinfo/templates/beerinfo/purchase_detail.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Purchase - {{ purchase }}
{% endblock %}

{% block content %}
    <h2>{{ purchase }}</h2>
    <ul class="inline">
        {% if perms.beerinfo.change_purchase %}
            <li><a href="{{ purchase.get_update_url }}"
                   class="button">
                    Edit Purchase</a></li>
        {% endif %}
        {% if perms.beerinfo.delete_purchase %}
            <li><a href="{{ purchase.get_delete_url }}"
                   class="button">
                    Delete Purchase</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Customer:</th>
                <td><a href="{{ customer.get_absolute_url }}">{{ customer }}</a> </td>
            </tr>
            <tr>
                <th>Staff:</th>
                <td><a href="{{ staff.get_absolute_url }}">{{ staff }}</a> </td>
            </tr>
            <tr>
                <th>Beer:</th>
                <td><a href="{{ beer.get_absolute_url }}">{{ beer }}</a> </td>
            </tr>
            <tr>
                <th>Bar:</th>
                <td><a href="{{ bar.get_absolute_url }}">{{ bar }}</a> </td>
            </tr>
            <tr>
                <th>Total:</th>
                <td>{{ purchase.total }}</td>
            </tr>
        </table>
    </section>
    <p>
        Return to <a href="{% url 'beerinfo_purchase_list_urlpattern' %}">Purchase List</a>.
    </p>
{% endblock %}

beerinfo/templates/beerinfo/purchase_update.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Update Purchase
{% endblock %}

{% block content %}
    <form
        action="{{ purchase.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Purchase</button>
    </form>
{% endblock %}

beerinfo/templates/beerinfo/staff_confirm_delete.html
{% extends 'beerinfo/base.html' %}

{% block title %}
Delete Staff
{% endblock %}

{% block content %}
    <form
        action="{{ staff.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p> Are you sure that you want to delete staff {{ staff }}?
        </p>
        <a href="{{ staff.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Staff</button>
    </form>
{% endblock %}

beerinfo/templates/beerinfo/staff_refuse_delete.html
{% extends 'beerinfo/base.html' %}

{% block title %}
Error Deleting Staff
{% endblock %}

{% block content %}
	<div>
		<h2>Error Deleting Staff</h2>
		<p>
            You may not delete staff {{ staff }}. This bar is currently associated with the following bar:
        </p>
        <ul>{% for bar in bars %}
            <li><a href="{{ staff.get_absolute_url }}">
                {{ beer }}</a></li>{%  endfor %}
        </ul>
        <p>
            Return to <a href="{% url 'beerinfo_staff_list_urlpattern' %}">Staff List</a>.
        </p>
    </div>
{% endblock %}

beerinfo/templates/beerinfo/staff_update.html
{% extends 'beerinfo/base.html' %}

{% block title %}
    Update Staff
{% endblock %}

{% block content %}
    <form
        action="{{ staff.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Staff</button>
    </form>
{% endblock %}